# Generated by Django 5.2.6 on 2026-01-21 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('summary', models.TextField(verbose_name='Tóm tắt nội dung')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nguồn tin')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Hình ảnh')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn Đọc thêm')),
                ('is_store_info', models.BooleanField(default=False, verbose_name='Là thông tin cửa hàng')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức & Cập nhật',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment_VNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ Admin')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chương trình')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Phần trăm giảm (%)')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaign_banners/', verbose_name='Banner khuyến mãi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Danh mục giảm giá')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('completed', 'Đã thanh toán'), ('failed', 'Thất bại'), ('shipped', 'Đang giao hàng')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='vnpay', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('chip_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chip xử lý (ví dụ: M1, M2 Pro)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_new', models.BooleanField(default=False, verbose_name='Sản phẩm mới')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Bán chạy nhất')),
                ('warranty_months', models.IntegerField(default=12, verbose_name='Bảo hành (tháng)')),
                ('shipping_info', models.CharField(default='Miễn phí toàn quốc', max_length=255, verbose_name='Thông tin vận chuyển')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('comment', models.TextField(verbose_name='Nội dung bình luận')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=50, verbose_name='Dung lượng (GB/TB)')),
                ('color', models.CharField(max_length=50, verbose_name='Màu sắc')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán (VNĐ)')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Phần trăm giảm giá (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='iphone_images/', verbose_name='Ảnh biến thể')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='home.product', verbose_name='Sản phẩm gốc')),
            ],
            options={
                'verbose_name_plural': 'Biến thể sản phẩm',
                'ordering': ['price'],
                'unique_together': {('product', 'storage', 'color')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Thuộc tính (ví dụ: Màn hình, Chip xử lý)')),
                ('value', models.CharField(max_length=255, verbose_name='Giá trị (ví dụ: OLED 6.5 inches, Apple A13 Bionic)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='home.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Thông số kỹ thuật',
                'verbose_name_plural': 'Thông số kỹ thuật',
                'ordering': ['product', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền giảm (VNĐ)')),
                ('description', models.CharField(help_text='Nội dung thông báo cho người dùng', max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
