# Generated by Django 5.2.6 on 2026-01-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
