# Generated by Django 5.2.6 on 2025-12-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_VNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
