# Generated by Django 6.0 on 2026-01-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactmessage_order_orderitem_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chương trình')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Phần trăm giảm (%)')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaign_banners/', verbose_name='Banner khuyến mãi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Danh mục giảm giá')),
            ],
        ),
    ]
