# Generated by Django 6.0 on 2026-01-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
